# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TimesApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TimesApp
#  pod 'PromiseKit', '~> 6.8'
#  pod 'Alamofire'
  pod 'SwiftLint'
  pod 'PromiseKit/Alamofire'
  
  target 'TimesAppTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'PromiseKit/Alamofire'
    
  end
end
